#!/usr/bin/env bash
# ai-kit -> OpenAI Codex CLI adapter (POSIX parity of sync.ps1).
# Category-1, additive, Claude-untouched. Verified vs codex-cli 0.130.0 (2026-05-17).
# See ./README.md and ./sync.ps1 for the authoritative design. Windows uses sync.ps1.
set -euo pipefail

DRY=0; PRUNE=0; FORCE=0
for a in "$@"; do case "$a" in
  --dry-run) DRY=1 ;; --prune) PRUNE=1 ;; --force) FORCE=1 ;;
  *) echo "unknown arg: $a" >&2; exit 2 ;;
esac; done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SKILLS_SRC="$REPO_ROOT/skills"
AGENTS_SRC="$REPO_ROOT/agents"
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
SKILLS_ROOT="$CODEX_HOME/skills"
GEN_MARKER=".ai-kit-generated"
VALIDATOR="$CODEX_HOME/skills/.system/skill-creator/scripts/quick_validate.py"

echo; echo "ai-kit -> Codex adapter"
echo "  repo        : $REPO_ROOT"
echo "  skills root : $SKILLS_ROOT"
echo "  mode        : $([ $DRY -eq 1 ] && echo 'DRY RUN' || echo apply)"; echo
[ -d "$SKILLS_SRC" ] || { echo "canonical skills dir not found: $SKILLS_SRC" >&2; exit 1; }
[ $DRY -eq 1 ] || mkdir -p "$SKILLS_ROOT"

issues=0

# 1. Skills: per-skill symlink
for s in "$SKILLS_SRC"/*/; do
  name="$(basename "$s")"; link="$SKILLS_ROOT/$name"; tgt="${s%/}"
  if [ -e "$link" ] || [ -L "$link" ]; then
    if [ -L "$link" ]; then
      cur="$(readlink "$link")"
      if [ "$cur" = "$tgt" ]; then echo "  ok       skill  $name"; continue; fi
      if [ $FORCE -ne 1 ]; then echo "  conflict skill  $name (-> $cur; use --force)"; issues=$((issues+1)); continue; fi
      [ $DRY -eq 1 ] || rm "$link"   # removes the symlink only, never its target
    else
      echo "  skip     skill  $name (real dir, not kit-owned)"; continue
    fi
  fi
  if [ $DRY -eq 1 ]; then echo "  would-link skill $name"; else ln -s "$tgt" "$link"; echo "  linked   skill  $name"; fi
done

# 2. Agents -> generated Codex skills
to_title(){ echo "$1" | tr '-' ' ' | awk '{for(i=1;i<=NF;i++)$i=toupper(substr($i,1,1)) substr($i,2)}1'; }
if [ -d "$AGENTS_SRC" ]; then
  for a in "$AGENTS_SRC"/*.md; do
    [ -e "$a" ] || continue
    name="$(awk -F': *' '/^name:/{print $2; exit}' "$a" | tr -d '"\r')"
    desc="$(awk -F': *' '/^description:/{sub(/^description: */,""); print; exit}' "$a" | tr -d '\r')"
    [ -n "$name" ] && [ -n "$desc" ] || { echo "  error    agent  $(basename "$a") (missing name/description)"; issues=$((issues+1)); continue; }
    dest="$SKILLS_ROOT/$name"
    if [ -d "$dest" ] && [ ! -f "$dest/$GEN_MARKER" ]; then echo "  skip     agent  $name (exists, not kit-generated)"; continue; fi
    if [ $DRY -eq 1 ]; then echo "  would-gen agent $name"; continue; fi
    mkdir -p "$dest/agents"
    body="$(awk 'BEGIN{n=0} /^---[[:space:]]*$/{n++; next} n>=2{print}' "$a")"
    { printf -- '---\nname: %s\ndescription: %s\n---\n\n' "$name" "$desc"; printf '%s\n' "$body"; } > "$dest/SKILL.md"
    { echo "# Generated by adapters/codex/sync.sh from agents/$(basename "$a") — do not hand-edit.";
      echo "interface:"; echo "  display_name: \"$(to_title "$name")\"";
      echo "  default_prompt: \"Use \$$name as a worker sub-agent; it follows its bound skill.\"";
      echo "policy:"; echo "  allow_implicit_invocation: false"; } > "$dest/agents/openai.yaml"
    echo "source: agents/$(basename "$a")" > "$dest/$GEN_MARKER"
    echo "  generated agent  $name (implicit-invocation off)"
  done
fi

# 3. AGENTS.md hint (never silent)
echo; echo "AGENTS.md: global read-location is [verify]. Link/copy per project, or globally:"
echo "  $SCRIPT_DIR/AGENTS.md  ->  <project>/AGENTS.md   (or $CODEX_HOME/AGENTS.md if supported)"

# 4. Validation (advisory, NEVER gates). Self-test first: a missing/broken
# python3 or PyYAML must degrade to "skipped", not mark skills FAIL.
echo
val_ok=0
if [ -f "$VALIDATOR" ] && command -v python3 >/dev/null 2>&1; then
  if st="$(python3 "$VALIDATOR" "$SKILLS_ROOT/.system/skill-creator" 2>&1)" && echo "$st" | grep -qi valid; then
    val_ok=1
  else
    echo "  validation skipped — validator self-test failed (host python issue): $(echo "$st" | tr '\n' ' ')"
  fi
else
  echo "  validation skipped — quick_validate.py or python3 unavailable"
fi
if [ $val_ok -eq 1 ]; then
  for d in "$SKILLS_ROOT"/*/; do
    n="$(basename "$d")"; [ "$n" = ".system" ] && continue
    if ! out="$(python3 "$VALIDATOR" "$d" 2>&1)"; then echo "  VALIDATE FAIL $n: $(echo "$out" | tr '\n' ' ')"; issues=$((issues+1)); fi
  done
  echo "  validator self-test OK — per-skill results above"
else
  echo "  (host-python problem only — junctions/generation unaffected; validate from Codex if wanted)"
fi

# Prune (report-only unless --force)
if [ $PRUNE -eq 1 ]; then
  echo; echo "Prune (kit-owned orphans):"
  for d in "$SKILLS_ROOT"/*/; do
    n="$(basename "$d")"; [ "$n" = ".system" ] && continue
    kit=0
    if [ -L "${d%/}" ] && [ "$(readlink "${d%/}")" = "$SKILLS_SRC/$n" ]; then kit=1; fi
    [ -f "$d/$GEN_MARKER" ] && kit=1
    [ $kit -eq 1 ] || continue
    if [ -d "$SKILLS_SRC/$n" ] || [ -f "$AGENTS_SRC/$n.md" ]; then continue; fi
    if [ $FORCE -eq 1 ] && [ $DRY -ne 1 ]; then
      [ -L "${d%/}" ] && rm "${d%/}" || rm -rf "$d"; echo "  removed orphan: $n"
    else echo "  orphan (use --prune --force): $n"; fi
  done
fi

echo
[ $issues -eq 0 ] && { echo "OK — restart Codex to pick up new skills."; exit 0; } \
                   || { echo "$issues issue(s) reported (not auto-fixed — canonical edits are Category-2)."; exit 1; }
